language: cpp

compiler:
  - clang
  - gcc
  - i686-w64-mingw32-gcc

before_install:
  # https://github.com/tyoc213/secret-wokie2/blob/master/.travis.yml
  - sudo apt-get install -qq x11proto-xf86vidmode-dev xorg-dev libglu1-mesa-dev

script:
  - cd simple_mesh
  - cmake CMakeLists.txt
  - make
  - cd ..
  - cd text_billboard
  - cmake CMakeLists.txt
  - make
  - cd ..
  - cd text_label
  - cmake CMakeLists.txt
  - make
  - cd ..
  - cd vincent_font
  - cmake CMakeLists.txt
  - make
  - cd ..
